[project]

repo_url = "https://github.com/HB9HIL/testdocs"
repo_name = "HB9HIL/testdocs"
site_name = "HB9HIL Testdocs"
site_description = "Testing Documentation"
site_author = "The Wavelog Dev Team and it's community"
site_url = "https://testdocs.hb9hil.org/"

copyright = """
Copyright &copy; 2026 Wavelog
"""

extra_css = ["stylesheets/extra.css"]

nav = [
  "index.md",
  {"Getting Started" = [
    {"Installation" = [
      "getting-started/installation/linux.md",
      "getting-started/installation/docker.md",
      "getting-started/installation/windows-wamp.md",
      "getting-started/installation/raspberry-pi.md",
      "getting-started/installation/raspberry-pi-image.md",
      "getting-started/installation/freebsd.md",
      "getting-started/installation/openbsd.md",
    ]},
    "getting-started/updating.md",
    "getting-started/hints-and-tips.md",
    "getting-started/version-info.md",
  ]},
  {"Configuration" = [
    "configuration/config-php.md",
    "configuration/wavelog-php.md",
    "configuration/global-options.md",
    "configuration/https.md",
    "configuration/webserver.md",
    "configuration/multi-domain.md",
    "configuration/centralized-userdata.md",
    "configuration/maptile-server.md",
  ]},
  {"Logbook" = [
    "logbook/dashboard.md",
    "logbook/logging.md",
    "logbook/logbook.md",
    "logbook/advanced-logbook.md",
    "logbook/qso-details.md",
    "logbook/simple-fle.md",
    "logbook/qso-modes.md",
    "logbook/keyboard-shortcuts.md",
  ]},
  {"Features" = [
    "features/analytics.md",
    "features/notes.md",
    "features/search.md",
    "features/statistics.md",
    "features/quick-lookup.md",
    "features/dx-cluster.md",
    "features/dx-waterfall.md",
    "features/themes.md",
    "features/widgets.md",
    "features/last-qsos-widget.md",
    "features/on-air-widget.md",
    "features/static-maps.md",
    "features/hams-of-note.md",
    "features/qrb-calculator.md",
    "features/kml-files.md",
  ]},
  {"Awards" = [
    "awards/dxcc.md",
    "awards/iota.md",
    "awards/sota.md",
    "awards/sota-csv-export.md",
    "awards/vucc.md",
    "awards/cq.md",
    "awards/was.md",
    "awards/dok.md",
    "awards/wab.md",
    "awards/wap.md",
  ]},
  {"Contesting" = [
    "contesting/post-contest-cbr.md",
    "contesting/adif-before-cbr.md",
  ]},
  {"QSL Management" = [
    "qsl/adif-import-export.md",
    "qsl/lotw.md",
    "qsl/lotw-import-export.md",
    "qsl/lotw-sync.md",
    "qsl/eqsl.md",
    "qsl/qrz-logbook.md",
    "qsl/hrdlog.md",
    "qsl/clublog-setup.md",
    "qsl/clublog-upload.md",
    "qsl/oqrs.md",
    "qsl/label-printing.md",
    "qsl/print-requested-qsls.md",
  ]},
  {"Integrations" = [
    "integrations/callsign-lookup.md",
    "integrations/radio-interface.md",
    "integrations/wsjt-x.md",
    "integrations/winkey.md",
    "integrations/log4om.md",
    "integrations/darc-dcl.md",
    "integrations/third-party-tools.md",
  ]},
  {"Administration" = [
    "administration/user-accounts.md",
    "administration/authentication.md",
    "administration/station-profiles.md",
    "administration/station-profiles-deep-dive.md",
    "administration/station-setup.md",
    "administration/clubstations.md",
    "administration/external-clubstations.md",
    "administration/recommended-setup-clubs.md",
    "administration/backup.md",
    "administration/backup-strategies.md",
    "administration/cron-jobs.md",
    "administration/maintenance-mode.md",
    "administration/debug.md",
    "administration/update-country-files.md",
    "administration/error-logging.md",
    "administration/password-reset.md",
    "administration/server-migration.md",
  ]},
  {"Migration" = [
    "migration/cloudlog-to-wavelog.md",
    "migration/restore-cloudlog-sql.md",
    "migration/cloudlog-to-wavelog-deprecated.md",
  ]},
  {"Developer" = [
    "developer/api.md",
    "developer/development-notes.md",
    "developer/style-guide.md",
    "developer/translations.md",
  ]},
  {"Troubleshooting" = [
    "troubleshooting/adif-cant-import.md",
    "troubleshooting/lotw-p12-upload.md",
    "troubleshooting/no-realtime-qso-upload.md",
    "troubleshooting/migration-locked.md",
    "troubleshooting/theme-issues.md",
    "troubleshooting/cloudlog-developer-mode.md",
    "troubleshooting/random-notes.md",
  ]},
]

[project.theme]

favicon = "images/favicon.ico"

language = "en"

features = [
    "content.action.edit",
    "content.action.view",
    "search.suggest",
    "search.highlight",
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.tracking",
    # "navigation.tabs",
    "navigation.path",
    "navigation.prune",
    "navigation.indexes",
    "navigation.top",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"


[project.theme.icon]
repo = "fontawesome/brands/github"

# ----------------------------------------------------------------------------
# You can configure your own logo to be shown in the header using the "logo"
# option in the "icons" subsection. The logo can be a path to a file in your
# "docs_dir" or it can be a path to an icon.
#
# Likewise, you can customize the logo used for the repository section of the
# header. Zensical derives the default logo for this from the repository URL.
# See below...
#
# There are other icons you can customize. See the documentation for details.
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons
# - https://zensical.org/docs/authoring/icons-emojis/#search
# ----------------------------------------------------------------------------
#[project.theme.icon]
#logo = "lucide/smile"
#repo = "lucide/smile"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/HB9HIL/testdocs"


